KEY_TARGET="target"

KEY_ID = "id"
KEY_TYPE = "type"
KEY_UNIT = "unit"
KEY_STEP = "step"
KEY_NAME = "name"
KEY_INPUTS = "inputs"
KEY_OUTPUTS = "outputs"
KEY_AUTHORS = "authors"
KEY_VERSION = "version"
KEY_FORMALISM = "formalism"
KEY_LOOKAHEAD = "lookahead"
KEY_PARAMETERS = "parameters"
KEY_DESCRIPTION = "description"
KEY_MINIMUM_STEP = "minimumstep"
KEY_SUPER_DENSE_TIME = "superdensetime"